TOKENIZER_LABEL_PICKLE_PATH: 'models/tokenizer_cnn.pickle'
MODEL_PATH: 'models/wildcard_cnn.hdf5'
MAX_SEQUENCE_LENGTH: 800
model_s3_bucket : 'pq-wildcardtf-models-stg.practicallogix.com'
model_local_dir : 'models'
threshold_cutoff : 0.3
tags : {'65+': 'qual',
 'absurdism': 'macro',
 'ancient wisdom': 'mega',
 'architecture': 'beat',
 'art': 'beat',
 'artletics': 'macro',
 'aspiration': 'macro',
 'auto': 'beat',
 'background as foreground': 'macro',
 'beauty': 'beat',
 'big data': 'beat',
 'biomimicry': 'macro',
 'blurred id': 'mega',
 'blurred responsibility': 'macro',
 'books & publications': 'beat',
 'boomers': 'qual',
 'brand activist': 'macro',
 'brand civil servants': 'macro',
 'brand elasticity': 'qual',
 'business': 'beat',
 'camera culture': 'macro',
 'clean': 'macro',
 'constant connection': 'macro',
 'cross-culturalism': 'macro',
 'crowd economy': 'mega',
 'data divinity': 'mega',
 'decor': 'beat',
 'defictionalization': 'macro',
 'design': 'beat',
 'digital detox': 'macro',
 'digital immortality': 'macro',
 'drone economy': 'macro',
 'eco hacking': 'macro',
 'edible tech': 'macro',
 'education': 'beat',
 'energy': 'beat',
 'environment': 'beat',
 'ephemeral': 'macro',
 'ethics': 'beat',
 'events': 'qual',
 'extrasensory': 'macro',
 'extreme safety': 'macro',
 'extremism': 'mega',
 'fashion & style': 'beat',
 'finance': 'beat',
 'fitness': 'beat',
 'flattening': 'macro',
 'food & beverage': 'beat',
 'foster tech': 'macro',
 'frictionless': 'mega',
 'futurology': 'beat',
 'gaming': 'beat',
 'gen x': 'qual',
 'gen y': 'qual',
 'gen z': 'qual',
 'gender identities': 'beat',
 'globals': 'mega',
 'hack life': 'mega',
 'health': 'beat',
 'hospitality': 'beat',
 'human premium': 'macro',
 'hyperculture': 'mega',
 'icon toppling': 'mega',
 'immersive': 'macro',
 'imperfect': 'macro',
 'income gap': 'mega',
 'kidult': 'mega',
 'life logic': 'macro',
 'living matter': 'mega',
 'longevity': 'mega',
 'low rez': 'macro',
 'luxury': 'beat',
 'magic': 'macro',
 'marketing': 'beat',
 'mashup': 'mega',
 'maximalism': 'macro',
 'memory management': 'macro',
 'micro tribes': 'macro',
 'mind management': 'mega',
 'minority groups': 'beat',
 'minority majority': 'mega',
 'mixed reality': 'macro',
 'moodgeisting': 'macro',
 'moral imperative': 'mega',
 'movies': 'beat',
 'music': 'beat',
 'nano': 'mega',
 'neo-celebrity': 'macro',
 'neural': 'macro',
 'new masculinity': 'mega',
 'new semantics': 'mega',
 'new sobriety': 'macro',
 "noah's archive": 'macro',
 'open': 'macro',
 'outsiders welcome': 'macro',
 'parenting': 'beat',
 'patents': 'beat',
 'perceptual diversity': 'macro',
 'play': 'macro',
 'pois': 'qual',
 'politics': 'beat',
 'power woman': 'mega',
 'provenance': 'mega',
 'quantified life': 'mega',
 'radical transparency': 'mega',
 'raw': 'macro',
 'refreshed classics': 'mega',
 'research innovation': 'qual',
 'retail': 'beat',
 'robots everywhere': 'mega',
 'science': 'beat',
 'self made': 'mega',
 'self-sustaning energy': 'macro',
 'sexuality': 'beat',
 'shadow world': 'macro',
 'shifting soils': 'mega',
 'simplexity': 'macro',
 'singletons': 'mega',
 'smallscaling': 'mega',
 'smart': 'mega',
 'snack media': 'mega',
 'social media': 'beat',
 'special interest': 'beat',
 'spirituality': 'beat',
 'sports': 'beat',
 'squealing': 'mega',
 'startups': 'beat',
 'super human': 'mega',
 'sustainability': 'mega',
 'taboo toppling': 'macro',
 'tangible intangible': 'mega',
 'tech drugs': 'macro',
 'technology': 'beat',
 'technomaladies': 'macro',
 'time poverty': 'macro',
 'transportation': 'beat',
 'tv': 'beat',
 'un-free': 'mega',
 'unapologetic': 'macro',
 'unmoney': 'mega',
 'urbanization': 'mega',
 'visceral': 'macro',
 'warm tech': 'macro',
 'waste positive': 'macro',
 'wellness design': 'macro',
 'work shift': 'mega'}